### ISSUE TITLE
issue in selecting the folder.

### ISSUE THREAD

**Issue by mukulvaidya** [dhanyn10/multiple-file-manager#55]
the path is not displayed on the app even after selecting the directory.
same happens with the sample app I have tried with the help of a book- 'Electron- beginner to pro'.
Please help.
![Screenshot from 2019-12-31 10-27-54](https://user-images.githubusercontent.com/50068294/71610589-4df37880-2bb8-11ea-928d-bdc4772440f0.png)

**Comment by dhanyn10** [comment]
i'll check it, thanks

**Comment by ranggaw1991** [comment]
Pada tanggal Sab, 11 Jan 2020 20:33, Dhany Nurdiansyah <
notifications@github.com> menulis:
